service: secret-hitler-role-bot

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  apiName: ${self:service}-api
  region: ${self:custom.env-default.REGION, self:custom.env-stage.REGION}
  iam:
    role: ${self:custom.env-default.LAMBDA_ROLE_ARN, self:custom.env-stage.LAMBDA_ROLE_ARN}
  logRetentionInDays: 90
  environment:
    FB_PAGE_ACCESS_TOKEN: ${self:custom.env-default.FB_PAGE_ACCESS_TOKEN, self:custom.env-stage.FB_PAGE_ACCESS_TOKEN}
    TELEGRAM_BOT_ACCESS_TOKEN: ${self:custom.env-default.TELEGRAM_BOT_ACCESS_TOKEN, self:custom.env-stage.TELEGRAM_BOT_ACCESS_TOKEN}
    TABLE_NAME: ${self:custom.tableName}
    VERIFY_TOKEN: ${self:custom.env-default.VERIFY_TOKEN, self:custom.env-stage.VERIFY_TOKEN}
    STAGE: ${self:provider.stage}
    VERSION: ${file(version.js):VERSION, 'UNKNOWN'}

custom:
  tableName: ${self:service}-${self:provider.stage}-games
  env-stage: ${file(env.yml):${self:provider.stage}}
  env-default: ${file(env.yml):default}

functions:
  fb:
    description: A Lambda function to handle Facebook Messenger requests for the Secret Hitler Role Bot. Managed by Serverless.
    handler: src/handlers/facebook.handler
    events:
      - http:
          method: ANY
          path: /fb
  telegram:
    description: A Lambda function to handle Telegram requests for the Secret Hitler Role Bot. Managed by Serverless.
    handler: src/handlers/telegram.handler
    events:
      - http:
          method: ANY
          path: /telegram

package:
  patterns:
    - "!./**"
    - "src/**"
    - "node_modules/**"

resources:
  Resources:
    GamesTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: gameID
            AttributeType: "N" # Number
          - AttributeName: gameOwner
            AttributeType: "S" # String
        KeySchema:
          - AttributeName: gameID
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gameOwnerGSI
            KeySchema:
              - AttributeName: gameOwner
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
