name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout ${{ github.sha }}
      uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test