name: CI/CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  cd:
    if: github.ref == 'refs/heads/master'
    needs: ci
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVYML: ${{ secrets.ENVYML }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install serverless
        run: npm install -g serverless
      - name: Install production dependencies
        run: npm ci --production
      - name: Create env.yml
        run: echo "$ENVYML" > env.yml
      - name: Deploy to dev environment
        run: npm run deploy:dev
